### ISSUE TITLE
ye Kya hai bhai xD?

### ISSUE THREAD

**Issue by TheAp0cryphal** [pka420/resume-parser-backend#1]

**Comment by pka420** [comment]
> _No description provided._

Lol of all the places I thought you would contact.

**Comment by pka420** [comment]
Here is the context:
[Assigment (Golang).pdf](https://github.com/user-attachments/files/15848742/Assigment.Golang.pdf)

I am something of a go expert myself now.

**Comment by TheAp0cryphal** [comment]
Oh resume detail extractor, mujhe laga koi auto apply script hai.
